
obj-$(CONFIG_BLK_DEV_IDE_ICSIDE)	+= icside.o
obj-$(CONFIG_BLK_DEV_IDE_RAPIDE)	+= rapide.o
obj-$(CONFIG_BLK_DEV_IDE_BAST)		+= bast-ide.o
obj-$(CONFIG_BLK_DEV_CREATOR_IDE)	+= creator-pxa270-ide.o

EXTRA_CFLAGS	:= -Idrivers/ide
