#!/bin/sh
#
# start/stop inetd super server.
#
# chkconfig: 2345 20 20
#
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin
. /etc/init.d/functions
if ! [ -x /usr/sbin/telnetd ]; then
	exit 0
fi


case "$1" in
    start)
	echo -n "Starting internet superserver:"
	echo -n " telnetd " ; /usr/sbin/telnetd &
	echo "."
	;;
    stop)
	echo -n "Stopping internet superserver:"
	find_pid_kill /usr/sbin/telnetd 2
	echo - "."
	;;
    reload)
	echo -n "Reloading internet superserver:"
	echo -n " inetd "
	start-stop-daemon --stop --quiet --pidfile /var/run/inetd.pid --signal 1
	echo "."
	;;
    force-reload)
	$0 reload
	;;
    restart)
	echo -n "Restarting internet superserver:"
	echo " inetd "
	start-stop-daemon --stop --quiet --pidfile /var/run/inetd.pid
	checkportmap
	echo "starting internet superserver:"
	start-stop-daemon --start --quiet --pidfile /var/run/inetd.pid --exec /usr/sbin/inetd
	echo "."
	;;
    *)
	echo "Usage: /etc/init.d/inetd {start|stop|reload|restart}"
	exit 1
	;;
esac

exit 0

